name: merge
on: [push, pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    github-token: github.token

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0